### ISSUE TITLE
Need continue

### ISSUE THREAD

**Issue by FndNur1Labs** [BitcoinVBR/bitcoinV#3]
May I see what change and will pull commit on my code atm. This great.

**Comment by BitcoinVBR** [comment]
What do you mean what change? You can compare the latest release to Bitcoin's release:
https://github.com/bitcoin/bitcoin/tree/v0.20.0
This will show the diff between BitcoinV and Bitcoin.

**Comment by FndNur1Labs** [comment]
Thank for information
